# source tmux conf
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# increase size of visible session name
set -g status-left-length 20

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# vim
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# TPM List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'TechnicalDC/tmux-ayu-theme'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
